### ISSUE TITLE
Remove `cyclic.js`, it appears npm fixed the bug that needed it

### ISSUE THREAD

**Issue by balupton** [RobLoach/docpad-plugin-opengraph#1]
Hey @RobLoach, it seems npm fixed the bug somewhere in v2 of npm that required cyclic.js to exist. As such, a new version of this plugin that removes the `cyclic.js` file as well as the `package.json:scripts:preinstall` hook, would be great - as `cyclic.js` does slow down the install process, and is a possible point of failure, so removing it is much better.

**Comment by RobLoach** [comment]
:+1: Should we remove from cyclic too?

**Comment by balupton** [comment]
> Should we remove from cyclic too?

?... perhaps you mean remove cyclic from bevry/basebase? It's still there, however I've updated the README to indicate it is now optional - perhaps some random person is using npm v1 or something.

On a related note, the last two remaining projects where cyclic.js exists is taskgroup and projectz, I'm in the process of removing it from them now :)

**Comment by RobLoach** [comment]
*base , yes.

Nice! Glad that npm is improving, getting better, and simplifying things for everyone.
